name: arkup_edoo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  dartz: ^0.10.1
  go_router: ^16.0.0
  connectivity_plus: ^6.1.4
  signature: ^5.4.0
  sqflite: ^2.4.2
  drift: ^2.28.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  path: ^1.9.1
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  intl: ^0.20.2
  collection: ^1.18.0
  geolocator: ^12.0.0
  duration_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.0-dev.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
